version: "3.8"

services:
  action:
    network_mode: host

    image: zimagi/command
    build:
      context: .
      dockerfile: Dockerfile

    env_file: .env
    environment:
      ZIMAGI_HOST: localhost
      ZIMAGI_PORT: 5123
      ZIMAGI_USER: admin
      ZIMAGI_TOKEN: 999999999
      ZIMAGI_LOG_LEVEL: DEBUG

    volumes:
      - ./lib:/usr/local/lib/action

    command:
      - module/get
      - |
        module_key: core
