services:
  action:
    network_mode: host

    image: zimagi/command
    build:
      context: .
      dockerfile: Dockerfile

    env_file: .env
    volumes:
      - ./lib:/usr/local/lib/action

    command:
      - module/get
      - |
        module_key: core
